version: "3.8"

services:
  backend:
    build: ./backend
    container_name: task_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./vite-project
    container_name: task_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend